## build
# docker-compose build
## if problems with build try
# docker-compose down && docker-compose build --no-cache
## start dev server
# docker-compose up
## run interactively with one time command (shell)
# docker-compose run --rm officetimepwa bash
version: '3'
services:
  officetimepwa:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # If you specify image as well as build, then Compose names the built according to image
    image: officetimepwa.dev
    working_dir: /officetimepwa
    volumes:
      # mount current directory to container
      - $PWD:/officetimepwa:cached
      # exclude node_modules
      # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      - /officetimepwa/node_modules/
    # expose ports at host
    ports:
    - "8080:8080"